//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowCase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int idBill { get; set; }
        public int ID_User { get; set; }
        public int Balance { get; set; }
        public int Bonus { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
