//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowCase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProducerCats
    {
        public int ID_producer_cats { get; set; }
        public int Id_producer { get; set; }
        public int Id_category { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Producer Producer { get; set; }
    }
}
