//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowCase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProducerCats
    {
        public int ID_producer_cats { get; set; }
        public int Id_producer { get; set; }
        public int Id_category { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Producer Producer { get; set; }
    }
}
