//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowCase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SilpoDBEntities : DbContext
    {
        public SilpoDBEntities()
            : base("name=SilpoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Prices> Prices { get; set; }
        public virtual DbSet<Producer> Producer { get; set; }
        public virtual DbSet<ProducerCats> ProducerCats { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Sell> Sell { get; set; }
        public virtual DbSet<ShopBank> ShopBank { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
