//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowCase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int ID_storage { get; set; }
        public int Id_product { get; set; }
        public int id_supply { get; set; }
        public int Available_items { get; set; }
        public System.DateTime FinalDate { get; set; }
    
        public virtual Supply Supply { get; set; }
    }
}
