//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Id_bill { get; set; }
        public int Balance { get; set; }
        public int Bonus { get; set; }
        public int ID_user { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
