//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.ProducerCats = new HashSet<ProducerCats>();
            this.Product = new HashSet<Product>();
        }
    
        public int ID_category { get; set; }
        public string Name { get; set; }
    
<<<<<<< HEAD
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProducerCats> ProducerCats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
=======
        public virtual ICollection<ProducerCats> ProducerCats { get; set; }
>>>>>>> 0ff800bd4265e19416227d2fb40d8c496dedd282
        public virtual ICollection<Product> Product { get; set; }
    }
}
