//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public Supply()
        {
            this.Storage = new HashSet<Storage>();
        }
    
        public int ID_supply { get; set; }
        public int Id_product { get; set; }
        public decimal Price { get; set; }
        public int MarkUp { get; set; }
        public int Amount { get; set; }
        public System.DateTime Date_made { get; set; }
        public System.DateTime Date_supply { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<Storage> Storage { get; set; }
    }
}
